### ISSUE TITLE
Please STOP modifying the codes directly on the master branche before testing it

### ISSUE THREAD

**Issue by SHADOW-13-WALKER** [notmarek/BeFake#100]
I have noticed that a lot of modifications happened lately to the code which made a lot of commands not working correctly, I'm running an old version of the code that I haven't updated since March and I have to say this : It works better than the current one !!!
So please, if you want to modify something, do it on a separate branche and test EVERY command command before merging it to the main one !

Thank You

**Comment by Smart123s** [comment]
Whilst I agree that submitting code without testing is bad practice, it will probably happen even if everyone tries to do their best to avoid it.

However, multiple solutions came up to make the effect of buggy code on the master branch less noticable: https://github.com/notmarek/BeFake/issues/92 and https://github.com/notmarek/BeFake/issues/60.
However, the thing is that the code on the master branch has some bugs, even as of writing this comment (ex https://github.com/notmarek/BeFake/issues/78).

So I guess the priority list is as follows:
1. Make the code stable (and implement any breaking changes before the next step)
2. Start proper versioning (with the possibility of backported fixes?)
3. Write unit test

What makes things even harder is that BeReal might change its API without notice, so the code that currently works may not work in 2 months time. So even with proper versioning, some breakages are unavoidable.

And also, doing any of the things mentioned above takes a lot of time, especially for a hobby project.

For now, you can either not update the pip package, don't repull the docker image, or (what I do) you can bind the docker image's version by specifying it's sha256.
