### ISSUE TITLE
 a couple be real

### ISSUE THREAD

**Issue by Igor636965736c610a** [notmarek/BeFake#102]
Will something be added to save how someone added a few beReali because they added such an option? :D. 
When I looked at the postman, I don't see the other beReals that are swiped left in the application so I wouldn't be able to write and solve it becous i dont know how
PS 
I appreciate your work because you probably have none of it

**Comment by chemokita13** [comment]
Hi! Maybe you are using an incorect method. You have to use get_friendsv1_feed(); not get_friends_feed()

**Comment by Igor636965736c610a** [comment]
@chemokita13 you mean - python befake.py feed friendsv1 or what? i dont understand how use get_friendsv1_feed() in cmd beFake.

**Comment by chemokita13** [comment]
Yeah, just type: python befake.py feed friends-v1
