### ISSUE TITLE
Enhancement: Second and third memory

### ISSUE THREAD

**Issue by jjj120** [notmarek/BeFake#109]
BeReal added the possibility to see the second and third BeReal in the memories in the app. 

I couldn't find that in the normal [https://mobile.bereal.com/api/feeds/memories](https://mobile.bereal.com/api/feeds/memories) api, but somewhere this data should now be accessible. 
I'm trying to find it, but I'm not sure how.

**Comment by jjj120** [comment]
I probably just found the right API, it is [https://mobile.bereal.com/api/feeds/memories-v1](https://mobile.bereal.com/api/feeds/memories-v1) (pretty simple :) ), there is the number of posts included. 
And there is a field `momentId`, which is probably how to get the other images

**Comment by jjj120** [comment]
Just found where to get the other posts, it's just in https://mobile.bereal.com/api/feeds/memories-v1/<'momentId'>, there you can get all the other images and post info.

Working on a pull request for the new memories-v1 api at [jjj120/BeFake/memories-v1](https://github.com/jjj120/BeFake/tree/memories-v1)

**Comment by jjj120** [comment]
Added pull request #110

**Comment by VxlerieUwU** [comment]
Me
