### ISSUE TITLE
Phone Number Formating Clarity.

### ISSUE THREAD

**Issue by starwarsman981** [notmarek/BeFake#112]
Phone numbers can be formatted in about a billion different ways, and the --help isn't giving any information on formating. I cannot start the login process because I am getting an error every single time.

Is it 1+ (123)456-7899
is it 11234567899
is it 1+ 123-456-7899
is it (123)4567899
There is little clarity and I'm unable to use anything currently because I cannot figure out how to format my phone number.

**Comment by SHADOW-13-WALKER** [comment]
Don't try to reinvent the wheel, do it like normal people do !! country code + phone number, no brackets or dashes needed

**Comment by starwarsman981** [comment]
so for a us it'd be in this format? 

11234567899

Thought I tried that but will do so again!
