### ISSUE TITLE
Viewing the posts in a nice way

### ISSUE THREAD

**Issue by ArtrenH** [notmarek/BeFake#25]
Currently, there is no way in this repo to visualise the data, that is being downloaded.
That's why I made an application with Flask that currently only displays posts of friends.
You can find it here, if you are interested: [https://github.com/ArtrenH/BeFake-Dashboard](https://github.com/ArtrenH/BeFake-Dashboard)

(Sorry for creating an Issue for that, I didn't find a better way to post this but I thought y'all could find it interesting.)

**Comment by notmarek** [comment]
Would you mind if I put a link to your project into the readme?

**Comment by s-alad** [comment]
Not to try and steal Artren's show, but I've also worked on a react client for viewing friend posts, comments, reactions based on many of the endpoints found here 
https://github.com/s-alad/toofake

**Comment by ArtrenH** [comment]
@notmarek That would be great, maybe you can just put @s-alads project in the Readme too.
