### ISSUE TITLE
question

### ISSUE THREAD

**Issue by pyp** [notmarek/BeFake#36]
is there an endpoint to search for a user with their username?

**Comment by AutMai** [comment]
Additionally maybe also to add that user.

**Comment by nikita-korovin** [comment]
> is there an endpoint to search for a user with their username?

Have you found any data on this?

**Comment by AutMai** [comment]
> > is there an endpoint to search for a user with their username?
> 
> Have you found any data on this?

Yeah!
POST
https://us-central1-alexisbarreyat-bereal.cloudfunctions.net/getUserProfile

with JSON body:

{
    "data": {
        "userName": "anyUserName"
    }
}

**Comment by pyp** [comment]
> 

 {'error': {'message': 'You must be authenticated.', 'status': 'UNAUTHENTICATED'}}

**Comment by AutMai** [comment]
> > 
> 
> {'error': {'message': 'You must be authenticated.', 'status': 'UNAUTHENTICATED'}}

you have to pass header {"authorization": "your_token"}

the same token as in Befake python class the self.token field

**Comment by pyp** [comment]
> > > 
> > 
> > 
> > {'error': {'message': 'You must be authenticated.', 'status': 'UNAUTHENTICATED'}}
> 
> you have to pass header {"authorization": "your_token"}
> 
> the same token as in Befake python class the self.token field

I did that but still aint workin

**Comment by pyp** [comment]
> > > 
> > 
> > 
> > {'error': {'message': 'You must be authenticated.', 'status': 'UNAUTHENTICATED'}}
> 
> you have to pass header {"authorization": "your_token"}
> 
> the same token as in Befake python class the self.token field

oop nvm got it,thanks

**Comment by nikita-korovin** [comment]
> > > is there an endpoint to search for a user with their username?
> > 
> > 
> > Have you found any data on this?
> 
> Yeah!
> 
> ```
> POST
> https://us-central1-alexisbarreyat-bereal.cloudfunctions.net/getUserProfile
> ```
> 
> with JSON body:
> 
> ```
> {
>     "data": {
>         "userName": "anyUserName"
>     }
> }
> ```

You are the BOSS!!!

**Comment by nikita-korovin** [comment]
Now getting 
{"error":"Forbidden","statusCode":403,"message":"Forbidden","errorKey":null,"fields":null,"timestamp":"2022-12-16T13:46:05.966Z","requestId":"b51399570c825451081157fa8f013f52"}
from any endpoint

**Comment by notmarek** [comment]
> Now getting
> {"error":"Forbidden","statusCode":403,"message":"Forbidden","errorKey":null,"fields":null,"timestamp":"2022-12-16T13:46:05.966Z","requestId":"b51399570c825451081157fa8f013f52"}
> from any endpoint

Are you sure your token isn't revoked? If not then we probably need to update headers.

**Comment by nikita-korovin** [comment]
No, it was not revoked, now getting this, from google this time
{
  "error": {
    "code": 400,
    "message": "INVALID_APP_CREDENTIAL : Invalid receipt.",
    "errors": [
      {
        "message": "INVALID_APP_CREDENTIAL : Invalid receipt.",
        "domain": "global",
        "reason": "invalid"
      }
    ]
  }
}
