### ISSUE TITLE
endpoints/functions to cancel friend requests or remove friends 

### ISSUE THREAD

**Issue by AutMai** [notmarek/BeFake#37]
Hey. It would we great to have a function which cancels sent friend requests by passing userId and same for removing a friend.

**Comment by nikita-korovin** [comment]
> Hey. It would we great to have a function which cancels sent friend requests by passing userId and same for removing a friend.

Does the app work for you? I cannot login

**Comment by AutMai** [comment]
> Does the app work for you? I cannot login

whats the error?

**Comment by nikita-korovin** [comment]
> > Does the app work for you? I cannot login
> 
> whats the error?

response from the https://www.googleapis.com endpoint
`{'error': {'code': 400, 'errors': [{'domain': 'global', 'message': 'APP_NOT_VERIFIED', 'reason': 'invalid'}], 'message': 'APP_NOT_VERIFIED'}}`
Im guessing now I should provide my own credentials

**Comment by nikita-korovin** [comment]
Ok logged in with my own creds!

**Comment by VxlerieUwU** [comment]
Looks like it applies a PATCH request to the following URL: https://mobile.bereal.com/api/relationships/friend-requests/userid

Here are my headers:
```

**Comment by VxlerieUwU** [comment]
I'll post the removing a friend one later, just have to inform one first 😸
