### ISSUE TITLE
Unable to log in 

### ISSUE THREAD

**Issue by heyyyyyyyyyyy1** [notmarek/BeFake#39]
When I try to log into my BeReal account I get the following error:
```
File "C:\___\BeFake\BeFake.py", line 95, in send_otp
    self.otp_session = res["sessionInfo"]
KeyError: 'sessionInfo'
```
I believe this is because `res` is returning the following data:
```
{'error': {'code': 400, 'message': 'INVALID_APP_CREDENTIAL : Invalid receipt.', 'errors': [{'message': 'INVALID_APP_CREDENTIAL : Invalid receipt.', 'domain': 'global', 'reason': 'invalid'}]}}
```
I have set up google API key, identity tools and firebase with phone authentication. 
What should I set the `iosReceipt` as? Do I need to change the `api_url` in the `BeFake` class?

**Comment by ProgiDE** [comment]
How did you write the command? 

``` befake login "+1**********"``` worked for me. The quotation marks are necessary.

**Comment by s-alad** [comment]
I have also been experiencing this issue and a lot others have, it seems the login process has changed

**Comment by ProgiDE** [comment]
> I have also been experiencing this issue and a lot others have, it seems the login process has changed

login works fine for me when i spell the command like i already said:
> ` befake login "+1**********"` worked for me. The quotation marks are necessary.

but i cant post anything
