### ISSUE TITLE
Gif upload

### ISSUE THREAD

**Issue by ArtrenH** [notmarek/BeFake#40]
Apparently, users can now react with gifs (seems to be an IOS-Update so far). I wasn't able to implement it just by changing every type in realmoji_picture.py from jpeg to gif (I could upload it but with only one frame), because the server afterwards didn't accept my request where I sent the url to the uploaded image (Bad argument error).

Does anyone know how to fix that and how to react with gifs via the API?

**Comment by VxlerieUwU** [comment]
Standard realmojis should work now since #52. Uploading animated webp images should be theoretically possible
