### ISSUE TITLE
Security Issue - Publicly Exposed API Key

### ISSUE THREAD

**Issue by tobynott80** [notmarek/BeFake#46]
In [BeFake.py](https://github.com/notmarek/BeFake/blob/master/BeFake/BeFake.py) on line 46 you have an exposed api key.
![image](https://user-images.githubusercontent.com/11465134/214361832-dad3190c-e8fc-45bb-8496-14e283abe32e.png)

Anyone with this key can make google api calls from your account - it might end up costing you money. Might be a good idea to revoke the key and change the code so that it pulls the api key through an environment variable instead.

**Comment by tobynott80** [comment]
![image](https://user-images.githubusercontent.com/11465134/214362426-3d3079a3-e3d2-459f-99cb-f6c9b3c92ded.png)
Looks like the quota is exceeded anyway. Oh well...

**Comment by notmarek** [comment]
> ![image](https://user-images.githubusercontent.com/11465134/214362426-3d3079a3-e3d2-459f-99cb-f6c9b3c92ded.png) Looks like the quota is exceeded anyway. Oh well...

This is an apikey extracted from the bereal app.
