### ISSUE TITLE
unable to login

### ISSUE THREAD

**Issue by LCB0B** [notmarek/BeFake#49]
I cannot manage to login : 

.....BeFake/BeFake/BeFake.py", line 99, in send_otp
    self.otp_session = res["sessionInfo"]
                       ~~~^^^^^^^^^^^^^^^
KeyError: 'sessionInfo'

**Comment by notmarek** [comment]
#43

**Comment by VxlerieUwU** [comment]
For some reason, it appears that the key used here has exceeded the rate limits of googles api.
`{'error': {'code': 400, 'message': 'QUOTA_EXCEEDED : Exceeded quota.', 'errors': [{'message': 'QUOTA_EXCEEDED : Exceeded quota.', 'domain': 'global', 'reason': 'invalid'}]}}`

**Comment by notmarek** [comment]
> For some reason, it appears that the key used here has exceeded the rate limits of googles api.
> 
> `{'error': {'code': 400, 'message': 'QUOTA_EXCEEDED : Exceeded quota.', 'errors': [{'message': 'QUOTA_EXCEEDED : Exceeded quota.', 'domain': 'global', 'reason': 'invalid'}]}}`
> 
> 

It's the key being used in the bereal apps on both android and iOS

**Comment by VxlerieUwU** [comment]
It could have been replaced? I'll look it up on the latest version

**Comment by VxlerieUwU** [comment]
Huh, I've got a new error `{'error': {'code': 400, 'message': 'INVALID_APP_CREDENTIAL', 'errors': [{'message': 'INVALID_APP_CREDENTIAL', 'domain': 'global', 'reason': 'invalid'}]}}`

**Comment by NicoWeio** [comment]
I just found https://github.com/torresflo/PyReal. In its README, it says:

> A common issue is to fail to send the phone number at the first step. This is usually due because quota was exceeded in the BeReal API. In this case, just retry until it works (it could take a couple of retry).

Indeed, trying the same command ~4 times back-to-back worked for me. If this reliably works after a few attempts, I'd suggest incorporating retries into BeFake, e.g. via https://github.com/jd/tenacity.
