### ISSUE TITLE
Endpoint for getting mutual friends

### ISSUE THREAD

**Issue by AutMai** [notmarek/BeFake#50]
Is there any endpoint to get userIds of mutualFriends?

I just have endpoints where the mutual friend count is exposed but there should also be one with the specific mutual friends.

**Comment by NicoWeio** [comment]
I'm new to the codebase, but this seems to be it:

https://github.com/notmarek/BeFake/blob/b5d21774272c7f890ac91affad941fb9a8f05e24/BeFake/BeFake.py#L159-L166

> friends of friends, this fails because it needs a whole new implementation because for some reason BeReal isn't using the same JSON tree :(

**Comment by VxlerieUwU** [comment]
> I'm new to the codebase, but this seems to be it:
> 
> https://github.com/notmarek/BeFake/blob/b5d21774272c7f890ac91affad941fb9a8f05e24/BeFake/BeFake.py#L159-L166
> 
> > friends of friends, this fails because it needs a whole new implementation because for some reason BeReal isn't using the same JSON tree :(

No, this is a feed with the posts from the friends of your friends. From what I understood, mutual friends is a list of users that can be found by querying user profiles.

**Comment by VxlerieUwU** [comment]
This can already be done by running befake.py get-user-profile

**Comment by AutMai** [comment]
the get-user-profile command uses the endpoint `https://mobile.bereal.com/api/person/profiles/{user_id}` but this endpoint returns the user with a field `relationship` containing `commonFriends`

But commonFriends contains only a sample of common friends and not all of them (there is a cap of 13)
So i get 13 friends but commonFriends also includes a count (19 in my case but only 13 in the list)

**Comment by LCB0B** [comment]
there is "relationships/suggestions", it is in the BeFake.py.
But it seems that friend suggestions has been deactivated, it outputs an empty list, and there isn't any suggestions the app either (at least for me)

**Comment by VxlerieUwU** [comment]
Maybe you don't have enough friends on BeReal or you didn't accept some privacy terms? I get many suggestions where mutualFriends is provided.

**Comment by AutMai** [comment]
i want to get the mutual friends of a single friend. so i get the userId from my friend, use get-user-profile with the id of my friend but i only get a maximum of 13 mutual friends but in the app it shows me 19 in total.
