### ISSUE TITLE
Api for send and deleting friend request 

### ISSUE THREAD

**Issue by hemangjoshi37a** [notmarek/BeFake#51]
Is there any api for send and deleting friend request ?

**Comment by VxlerieUwU** [comment]
#37

**Comment by VxlerieUwU** [comment]
Done! To send a friend request, run `befake.py new-friend-request <userId>` and to cancel one run `befake.py cancel-friend-request <userId>`

**Comment by hemangjoshi37a** [comment]
@VxlerieUwU Awesome brother.
