### ISSUE TITLE
New version/release, befake 1.1.0?

### ISSUE THREAD

**Issue by VxlerieUwU** [notmarek/BeFake#63]
Hello! A lot of code has been changed recently, I think it might be time to make a new release on PyPI and on GitHub. 
@notmarek let me know what you think, some things are still needed to be sorted out like instant realmojis, they currently do not work for me.

**Comment by VxlerieUwU** [comment]
Also we really need a roadmap: I have some plans with this project, like a GTK4 app for Linux desktop/mobile and full GCM push notification support on desktop environments to pave the way for more reverse-engineering of "private" APIs of mobile apps.

**Comment by notmarek** [comment]
> Hello! A lot of code has been changed recently, I think it might be time to make a new release on PyPI and on GitHub. 
> 
> @notmarek let me know what you think, some things are still needed to be sorted out like instant realmojis, they currently do not work for me. 

I will create a release when I get my computer fixed. Thanks for all the work you do <3
