### ISSUE TITLE
unable to login - INVALID_APP_CREDENTIAL

### ISSUE THREAD

**Issue by samma835** [notmarek/BeFake#66]
any one same with me?

`
{
    "error": {
        "code": 400,
        "message": "INVALID_APP_CREDENTIAL",
        "errors": [
            {
                "message": "INVALID_APP_CREDENTIAL",
                "domain": "global",
                "reason": "invalid"
            }
        ]
    }
}
`

**Comment by VxlerieUwU** [comment]
Can you give me the full error trace, I can't know precisely where it comes from without it

**Comment by samma835** [comment]
@VxlerieUwU  I masked some values, but I am sure they are correct

curl --location 'https://www.googleapis.com/identitytoolkit/v3/relyingparty/sendVerificationCode?key=******' \
--header 'user-agent: AlexisBarreyat.BeReal/0.35.0 (iPhone; iOS 16.0.2; Scale/2.00)' \
--header 'x-ios-bundle-identifier: AlexisBarreyat.BeReal' \
--header 'Content-Type: application/json' \
--data '{
    "phoneNumber": "+1******",
    "iosReceipt": "AEFDNu9Q******BNc1c",
    "iosSecret": "KKwu****u0z"
}'

**Comment by samma835** [comment]
Sorry for that. I find the reason. close.

**Comment by notmarek** [comment]
> Sorry for that. I find the reason. close.

Could you please share the reason? This kind of reply is completely useless and helps no one. Thank you.
