### ISSUE TITLE
BUG: get_users_by_phone_number assertion error

### ISSUE THREAD

**Issue by ohld** [notmarek/BeFake#69]
I tried several ways to call that function but all the time I get the assertion inside `api_request` method. Perhaps the API endpoint method is incorrectly tested. 

<img width="795" alt="image" src="https://user-images.githubusercontent.com/5613295/231159749-2c3045c3-18a4-4dc0-b3fb-e2ae8ee969a9.png">

I'd also rename this method to get_users_by_phone_number**s** because we pass a list of phone numbers, not just one.

**Comment by VxlerieUwU** [comment]
Fixed with d81086b27ae5e042cabd97cd2084ce4d13aade91.
