### ISSUE TITLE
Implement pagination to endpoints

### ISSUE THREAD

**Issue by ohld** [notmarek/BeFake#70]
> Sorry for bothering you about API and stuff. I don't have any Android device to sniff and BeReal iOS app uses client-side SSL pinning which cannot be captured.

I want to get all recommended friends, not just the first page. `bf.get_friend_suggestions()` calls `res = self.api_request("get", f"relationships/suggestions")` which response has `res["next"]` field which looks like this: `K2Cvai3i7rhdNhtqo3m1aAcYOT72`.

I tried to pass it as a 'next' param but it still returns the first pagination page. I think it would be better if someone with Android device can check the proper one.

``` python
res = bf.api_request("get", f"relationships/suggestions")
res = bf.api_request("get", f"relationships/suggestions", params={"next": res["next"]})
# still returns the first page
```

**Comment by VxlerieUwU** [comment]
Will do! Thank you for all your issues, it keeps the project active! On iOS, I think there's a way to repackage .ipa files with certificate pinning removed, iOS just seems unnecessarily complicated comparing to how easy it is to root Android phones.

**Comment by notmarek** [comment]
> Will do! Thank you for all your issues, it keeps the project active! On iOS, I think there's a way to repackage .ipa files with certificate pinning removed, iOS just seems unnecessarily complicated comparing to how easy it is to root Android phones.

I have just successfully unpinned the certificates on IOS!

**Comment by VxlerieUwU** [comment]
> > Will do! Thank you for all your issues, it keeps the project active! On iOS, I think there's a way to repackage .ipa files with certificate pinning removed, iOS just seems unnecessarily complicated comparing to how easy it is to root Android phones.
> 
> I have just successfully unpinned the certificates on IOS!

🎉🎉🎉🎉🎉🎉

**Comment by VxlerieUwU** [comment]
Done with 2ed19d7bd06822f84d59d0f9cf381eb0d54acf14
