### ISSUE TITLE
add_friend source arg needs examples

### ISSUE THREAD

**Issue by ohld** [notmarek/BeFake#76]
I think you need to provide examples of valid "source" values. I don't want to send a random string.
<img width="455" alt="image" src="https://user-images.githubusercontent.com/5613295/233784523-73686e2d-3dad-4a71-81e7-12f5bc9363a4.png">

https://github.com/notmarek/BeFake/blob/master/BeFake/BeFake.py#L254

Let's find out which sources are valid!

**Comment by VxlerieUwU** [comment]
You might want to take a look here! This project really needs some proper documentation. 

https://github.com/notmarek/BeFake/blob/58d4ec27767b0fb07df869ea6193a65c398fcb1e/BeFake/__main__.py#L354

**Comment by ohld** [comment]
By the way, source="contacts" produces 400 error. So I think it should be removed.
