### ISSUE TITLE
Add support for extra bereals

### ISSUE THREAD

**Issue by KoenMangelschots** [notmarek/BeFake#87]
The latest bereal version added support for users to post extra bereals if they posted their first bereal on time, but the current friends feed command does not seem to download these extra bereals.

**Comment by clam0r** [comment]
jup, that would be nice. They adeed a new friends feed endpoint https://mobile.bereal.com/api/feeds/friends-v1

**Comment by VxlerieUwU** [comment]
On it, together with the new friends-v1 endpoint.

**Comment by ohld** [comment]
I want to add a penny here: 
Please also add an endpoint to remove a friend. Right now, BeFake has only `add_friend` (which is 100% fine) and `remove_friend_request` (which produces 400, maybe already became broken).

**Comment by NicoWeio** [comment]
For future reference: This has been implemented in 416e1db198f7a557b87dd68ee51aa933ba0f16e5.
