### ISSUE TITLE
KeyError: 'notification_id'

### ISSUE THREAD

**Issue by terminator527** [notmarek/BeFake#99]
![Capture d'écran 2023-05-07 111237](https://user-images.githubusercontent.com/11898346/236668800-5ba996a6-f4d8-46b2-ae8b-23c0ebf0b9f2.png)

Hello, this problem appears when I want to retrieve the "feed friends". 
There is just this bug with this option. 
Does anyone know how to fix this?

Thanks in advance

**Comment by omtoi101** [comment]
Same here
code either throws
1
`File "/root/projects/snooper5.py", line 44, in __init__
    self.profile_picture = data_dict["user"].get("profilePicture", {}).get("url", "")
AttributeError: 'NoneType' object has no attribute 'get'`
or 2
`File "/usr/local/lib/python3.9/dist-packages/BeFake/__main__.py", line 197, in feed
    _realmoji_location = _realmoji_location.format(user=emoji.username, type=emoji.type, feed_id=feed_id,
KeyError: 'notification_id'`
errors when running `befake feed friends`

**Comment by VxlerieUwU** [comment]
Fixed with 2a112cce4489f7ceb81a3883b4eda7930106df2c
